# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration
# Modified Vagrantfile based on "gis-machine" from Github user "rburhum"
#
# https://github.com/rburhum/gis-machine

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Build based on Ubuntu Linux trusty64
  config.vm.box = "ubuntu/trusty64"

  # Setup SSH forwarding
  config.ssh.forward_x11 = true

  # Install requirements
  config.vm.provision "shell", :path => "./setup/bootstrap.sh"

  # Install TSTools
  config.vm.provision "shell", :path => "./setup/tstools.sh",
    privileged: false

  config.vm.synced_folder "../", "/tstools"

  # Specify 2GB of RAM and 1 CPU for VirtualBox VM
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    # vb.gui = true

    vb.customize [
                    "modifyvm", :id,
                    "--memory", "2048",
                    "--cpus", "1"
                 ]
  end
end
