# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Build based on Ubuntu Linux trusty64
  config.vm.box = "ubuntu/trusty64"

  # Setup SSH forwarding
  config.ssh.forward_x11 = true

  # Install requirements
  config.vm.provision "shell", :path => "./setup/bootstrap.sh"

  # Install TSTools
  config.vm.provision "shell", :path => "./setup/tstools.sh",
    privileged: false

  # Share folder with map source data
  # For reference, the first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../", "/tstools"

  # Specify 2GB of RAM and 1 CPU for VirtualBox VM
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    # vb.gui = true

    vb.customize [
                    "modifyvm", :id,
                    "--memory", "2048",
                    "--cpus", "1"
                 ]
  end
end
