# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_config.ui'
#
# Created: Mon Apr  8 20:57:02 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName(_fromUtf8("Config"))
        Config.resize(357, 490)
        self.gridLayout = QtGui.QGridLayout(Config)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lab_config = QtGui.QLabel(Config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab_config.setFont(font)
        self.lab_config.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_config.setObjectName(_fromUtf8("lab_config"))
        self.gridLayout.addWidget(self.lab_config, 0, 0, 1, 2)
        self.lineEdit_2 = QtGui.QLineEdit(Config)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 6, 0, 1, 2)
        self.label_3 = QtGui.QLabel(Config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 10, 0, 1, 2)
        self.button_location = QtGui.QPushButton(Config)
        self.button_location.setObjectName(_fromUtf8("button_location"))
        self.gridLayout.addWidget(self.button_location, 2, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(Config)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 4, 0, 1, 2)
        self.label_4 = QtGui.QLabel(Config)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 11, 0, 1, 2)
        self.label_2 = QtGui.QLabel(Config)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Config)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 16, 1, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lab_redband = QtGui.QLabel(Config)
        self.lab_redband.setMinimumSize(QtCore.QSize(150, 0))
        self.lab_redband.setObjectName(_fromUtf8("lab_redband"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lab_redband)
        self.lab_greenband = QtGui.QLabel(Config)
        self.lab_greenband.setMinimumSize(QtCore.QSize(150, 0))
        self.lab_greenband.setObjectName(_fromUtf8("lab_greenband"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lab_greenband)
        self.edit_greenband = QtGui.QLineEdit(Config)
        self.edit_greenband.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_greenband.setObjectName(_fromUtf8("edit_greenband"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.edit_greenband)
        self.lab_blueband = QtGui.QLabel(Config)
        self.lab_blueband.setMinimumSize(QtCore.QSize(150, 0))
        self.lab_blueband.setObjectName(_fromUtf8("lab_blueband"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lab_blueband)
        self.edit_blueband = QtGui.QLineEdit(Config)
        self.edit_blueband.setCursorPosition(5)
        self.edit_blueband.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_blueband.setObjectName(_fromUtf8("edit_blueband"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.edit_blueband)
        self.edit_redband = QtGui.QLineEdit(Config)
        self.edit_redband.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_redband.setObjectName(_fromUtf8("edit_redband"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.edit_redband)
        self.gridLayout.addLayout(self.formLayout, 12, 0, 1, 2)
        self.edit_location = QtGui.QLineEdit(Config)
        self.edit_location.setObjectName(_fromUtf8("edit_location"))
        self.gridLayout.addWidget(self.edit_location, 2, 0, 1, 1)
        self.rad_stretch_plot = QtGui.QRadioButton(Config)
        self.rad_stretch_plot.setObjectName(_fromUtf8("rad_stretch_plot"))
        self.gridLayout.addWidget(self.rad_stretch_plot, 15, 1, 1, 1)
        self.rad_stretch_sd = QtGui.QRadioButton(Config)
        self.rad_stretch_sd.setChecked(True)
        self.rad_stretch_sd.setAutoRepeat(False)
        self.rad_stretch_sd.setObjectName(_fromUtf8("rad_stretch_sd"))
        self.gridLayout.addWidget(self.rad_stretch_sd, 14, 1, 1, 1)
        self.label = QtGui.QLabel(Config)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lab_stretch_plot = QtGui.QLabel(Config)
        self.lab_stretch_plot.setObjectName(_fromUtf8("lab_stretch_plot"))
        self.gridLayout.addWidget(self.lab_stretch_plot, 15, 0, 1, 1)
        self.lab_stretch_sd = QtGui.QLabel(Config)
        self.lab_stretch_sd.setObjectName(_fromUtf8("lab_stretch_sd"))
        self.gridLayout.addWidget(self.lab_stretch_sd, 14, 0, 1, 1)
        self.lab_location = QtGui.QLabel(Config)
        self.lab_location.setObjectName(_fromUtf8("lab_location"))
        self.gridLayout.addWidget(self.lab_location, 1, 0, 1, 2)
        self.label_5 = QtGui.QLabel(Config)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 13, 0, 1, 2)

        self.retranslateUi(Config)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Config.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Config.reject)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        Config.setWindowTitle(QtGui.QApplication.translate("Config", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_config.setText(QtGui.QApplication.translate("Config", "Dataset Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("Config", "*stack", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Config", "Layer Display Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.button_location.setText(QtGui.QApplication.translate("Config", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("Config", "LND*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Config", "Default Bands", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Config", "Stack pattern:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_redband.setText(QtGui.QApplication.translate("Config", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_greenband.setText(QtGui.QApplication.translate("Config", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_greenband.setInputMask(QtGui.QApplication.translate("Config", "0000D; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_greenband.setText(QtGui.QApplication.translate("Config", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_blueband.setText(QtGui.QApplication.translate("Config", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_blueband.setInputMask(QtGui.QApplication.translate("Config", "0000D; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_blueband.setText(QtGui.QApplication.translate("Config", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_redband.setInputMask(QtGui.QApplication.translate("Config", "0000D; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_redband.setText(QtGui.QApplication.translate("Config", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.rad_stretch_plot.setText(QtGui.QApplication.translate("Config", "Use plot Y-limits", None, QtGui.QApplication.UnicodeUTF8))
        self.rad_stretch_sd.setText(QtGui.QApplication.translate("Config", "2 standard deviations", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Config", "Stack directory pattern:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_stretch_plot.setText(QtGui.QApplication.translate("Config", "Plot min/max:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_stretch_sd.setText(QtGui.QApplication.translate("Config", "Standard Deviations:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_location.setText(QtGui.QApplication.translate("Config", "Stacked time series location:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Config", "Default Stretch", None, QtGui.QApplication.UnicodeUTF8))

