# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_config.ui'
#
# Created: Wed Apr 17 13:30:24 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName(_fromUtf8("Config"))
        Config.resize(357, 568)
        self.gridLayout = QtGui.QGridLayout(Config)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(Config)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lab_redband = QtGui.QLabel(Config)
        self.lab_redband.setMinimumSize(QtCore.QSize(150, 0))
        self.lab_redband.setObjectName(_fromUtf8("lab_redband"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lab_redband)
        self.lab_greenband = QtGui.QLabel(Config)
        self.lab_greenband.setMinimumSize(QtCore.QSize(150, 0))
        self.lab_greenband.setObjectName(_fromUtf8("lab_greenband"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lab_greenband)
        self.edit_greenband = QtGui.QLineEdit(Config)
        self.edit_greenband.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_greenband.setObjectName(_fromUtf8("edit_greenband"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.edit_greenband)
        self.lab_blueband = QtGui.QLabel(Config)
        self.lab_blueband.setMinimumSize(QtCore.QSize(150, 0))
        self.lab_blueband.setObjectName(_fromUtf8("lab_blueband"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lab_blueband)
        self.edit_blueband = QtGui.QLineEdit(Config)
        self.edit_blueband.setCursorPosition(5)
        self.edit_blueband.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_blueband.setObjectName(_fromUtf8("edit_blueband"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.edit_blueband)
        self.edit_redband = QtGui.QLineEdit(Config)
        self.edit_redband.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edit_redband.setObjectName(_fromUtf8("edit_redband"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.edit_redband)
        self.gridLayout.addLayout(self.formLayout, 12, 0, 1, 2)
        self.label_5 = QtGui.QLabel(Config)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 13, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edit_location = QtGui.QLineEdit(Config)
        self.edit_location.setObjectName(_fromUtf8("edit_location"))
        self.horizontalLayout.addWidget(self.edit_location)
        self.button_location = QtGui.QPushButton(Config)
        self.button_location.setObjectName(_fromUtf8("button_location"))
        self.horizontalLayout.addWidget(self.button_location)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.lab_config = QtGui.QLabel(Config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab_config.setFont(font)
        self.lab_config.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_config.setObjectName(_fromUtf8("lab_config"))
        self.gridLayout.addWidget(self.lab_config, 0, 0, 1, 2)
        self.label_3 = QtGui.QLabel(Config)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 2)
        self.rad_stretch_sd = QtGui.QRadioButton(Config)
        self.rad_stretch_sd.setChecked(True)
        self.rad_stretch_sd.setAutoRepeat(False)
        self.rad_stretch_sd.setObjectName(_fromUtf8("rad_stretch_sd"))
        self.gridLayout.addWidget(self.rad_stretch_sd, 14, 1, 1, 1)
        self.lab_stretch_plot = QtGui.QLabel(Config)
        self.lab_stretch_plot.setObjectName(_fromUtf8("lab_stretch_plot"))
        self.gridLayout.addWidget(self.lab_stretch_plot, 15, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(Config)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 17, 0, 1, 2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lab_transparency = QtGui.QLabel(Config)
        self.lab_transparency.setObjectName(_fromUtf8("lab_transparency"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lab_transparency)
        self.combox_transparency = QtGui.QComboBox(Config)
        self.combox_transparency.setObjectName(_fromUtf8("combox_transparency"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.combox_transparency)
        self.gridLayout.addLayout(self.formLayout_2, 18, 0, 1, 2)
        self.label_4 = QtGui.QLabel(Config)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 11, 0, 1, 2)
        self.rad_stretch_plot = QtGui.QRadioButton(Config)
        self.rad_stretch_plot.setObjectName(_fromUtf8("rad_stretch_plot"))
        self.gridLayout.addWidget(self.rad_stretch_plot, 15, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Config)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 16, 0, 1, 2)
        self.edit_image = QtGui.QLineEdit(Config)
        self.edit_image.setText(_fromUtf8(""))
        self.edit_image.setObjectName(_fromUtf8("edit_image"))
        self.gridLayout.addWidget(self.edit_image, 4, 0, 1, 2)
        self.lab_stretch_sd = QtGui.QLabel(Config)
        self.lab_stretch_sd.setObjectName(_fromUtf8("lab_stretch_sd"))
        self.gridLayout.addWidget(self.lab_stretch_sd, 14, 0, 1, 1)
        self.label = QtGui.QLabel(Config)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lab_location = QtGui.QLabel(Config)
        self.lab_location.setObjectName(_fromUtf8("lab_location"))
        self.gridLayout.addWidget(self.lab_location, 1, 0, 1, 2)
        self.edit_stack = QtGui.QLineEdit(Config)
        self.edit_stack.setText(_fromUtf8(""))
        self.edit_stack.setObjectName(_fromUtf8("edit_stack"))
        self.gridLayout.addWidget(self.edit_stack, 6, 0, 1, 2)
        self.button_box = QtGui.QDialogButtonBox(Config)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.gridLayout.addWidget(self.button_box, 19, 1, 1, 1)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        Config.setWindowTitle(QtGui.QApplication.translate("Config", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Config", "Stack pattern:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_redband.setText(QtGui.QApplication.translate("Config", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_greenband.setText(QtGui.QApplication.translate("Config", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_greenband.setInputMask(QtGui.QApplication.translate("Config", "0000D; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_greenband.setText(QtGui.QApplication.translate("Config", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_blueband.setText(QtGui.QApplication.translate("Config", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_blueband.setInputMask(QtGui.QApplication.translate("Config", "0000D; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_blueband.setText(QtGui.QApplication.translate("Config", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_redband.setInputMask(QtGui.QApplication.translate("Config", "0000D; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_redband.setText(QtGui.QApplication.translate("Config", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Config", "Default Stretch", None, QtGui.QApplication.UnicodeUTF8))
        self.button_location.setText(QtGui.QApplication.translate("Config", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_config.setText(QtGui.QApplication.translate("Config", "Dataset Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Config", "Layer Display Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.rad_stretch_sd.setText(QtGui.QApplication.translate("Config", "2 standard deviations", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_stretch_plot.setText(QtGui.QApplication.translate("Config", "Plot min/max:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_transparency.setText(QtGui.QApplication.translate("Config", "Transparency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Config", "Default Bands", None, QtGui.QApplication.UnicodeUTF8))
        self.rad_stretch_plot.setText(QtGui.QApplication.translate("Config", "Use plot Y-limits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Config", "Clipping Options", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_stretch_sd.setText(QtGui.QApplication.translate("Config", "Standard Deviations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Config", "Stack directory pattern:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_location.setText(QtGui.QApplication.translate("Config", "Stacked time series location:", None, QtGui.QApplication.UnicodeUTF8))

